/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DadosCertificacaoRouteImport } from './routes/dados-certificacao'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ActionsRouteImport } from './routes/actions'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InscricaoTokenRouteImport } from './routes/inscricao.$token'
import { Route as EntidadeDashboardRouteImport } from './routes/entidade.dashboard'
import { Route as AdminProgramasRouteImport } from './routes/admin.programas'
import { Route as AdminManagerRouteImport } from './routes/admin.manager'
import { Route as AdminAcoesRouteImport } from './routes/admin.acoes'
import { Route as AuthenticatedRecursosRouteImport } from './routes/_authenticated/recursos'
import { Route as AuthenticatedAdminRecursosRouteImport } from './routes/_authenticated/admin.recursos'
import { Route as AuthenticatedActionsIdRouteImport } from './routes/_authenticated/actions.$id'
import { Route as ApiPublicRecursosSplatRouteImport } from './routes/api/public/recursos.$'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DadosCertificacaoRoute = DadosCertificacaoRouteImport.update({
  id: '/dados-certificacao',
  path: '/dados-certificacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsRoute = ActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricaoTokenRoute = InscricaoTokenRouteImport.update({
  id: '/inscricao/$token',
  path: '/inscricao/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EntidadeDashboardRoute = EntidadeDashboardRouteImport.update({
  id: '/entidade/dashboard',
  path: '/entidade/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProgramasRoute = AdminProgramasRouteImport.update({
  id: '/admin/programas',
  path: '/admin/programas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminManagerRoute = AdminManagerRouteImport.update({
  id: '/admin/manager',
  path: '/admin/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAcoesRoute = AdminAcoesRouteImport.update({
  id: '/admin/acoes',
  path: '/admin/acoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRecursosRoute = AuthenticatedRecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRecursosRoute =
  AuthenticatedAdminRecursosRouteImport.update({
    id: '/admin/recursos',
    path: '/admin/recursos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedActionsIdRoute = AuthenticatedActionsIdRouteImport.update({
  id: '/actions/$id',
  path: '/actions/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicRecursosSplatRoute = ApiPublicRecursosSplatRouteImport.update({
  id: '/api/public/recursos/$',
  path: '/api/public/recursos/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/auth': typeof AuthRoute
  '/dados-certificacao': typeof DadosCertificacaoRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/recursos': typeof AuthenticatedRecursosRoute
  '/admin/acoes': typeof AdminAcoesRoute
  '/admin/manager': typeof AdminManagerRoute
  '/admin/programas': typeof AdminProgramasRoute
  '/entidade/dashboard': typeof EntidadeDashboardRoute
  '/inscricao/$token': typeof InscricaoTokenRoute
  '/actions/$id': typeof AuthenticatedActionsIdRoute
  '/admin/recursos': typeof AuthenticatedAdminRecursosRoute
  '/api/public/recursos/$': typeof ApiPublicRecursosSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/auth': typeof AuthRoute
  '/dados-certificacao': typeof DadosCertificacaoRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/recursos': typeof AuthenticatedRecursosRoute
  '/admin/acoes': typeof AdminAcoesRoute
  '/admin/manager': typeof AdminManagerRoute
  '/admin/programas': typeof AdminProgramasRoute
  '/entidade/dashboard': typeof EntidadeDashboardRoute
  '/inscricao/$token': typeof InscricaoTokenRoute
  '/actions/$id': typeof AuthenticatedActionsIdRoute
  '/admin/recursos': typeof AuthenticatedAdminRecursosRoute
  '/api/public/recursos/$': typeof ApiPublicRecursosSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/actions': typeof ActionsRoute
  '/auth': typeof AuthRoute
  '/dados-certificacao': typeof DadosCertificacaoRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/_authenticated/recursos': typeof AuthenticatedRecursosRoute
  '/admin/acoes': typeof AdminAcoesRoute
  '/admin/manager': typeof AdminManagerRoute
  '/admin/programas': typeof AdminProgramasRoute
  '/entidade/dashboard': typeof EntidadeDashboardRoute
  '/inscricao/$token': typeof InscricaoTokenRoute
  '/_authenticated/actions/$id': typeof AuthenticatedActionsIdRoute
  '/_authenticated/admin/recursos': typeof AuthenticatedAdminRecursosRoute
  '/api/public/recursos/$': typeof ApiPublicRecursosSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actions'
    | '/auth'
    | '/dados-certificacao'
    | '/dashboard'
    | '/profile'
    | '/recursos'
    | '/admin/acoes'
    | '/admin/manager'
    | '/admin/programas'
    | '/entidade/dashboard'
    | '/inscricao/$token'
    | '/actions/$id'
    | '/admin/recursos'
    | '/api/public/recursos/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actions'
    | '/auth'
    | '/dados-certificacao'
    | '/dashboard'
    | '/profile'
    | '/recursos'
    | '/admin/acoes'
    | '/admin/manager'
    | '/admin/programas'
    | '/entidade/dashboard'
    | '/inscricao/$token'
    | '/actions/$id'
    | '/admin/recursos'
    | '/api/public/recursos/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/actions'
    | '/auth'
    | '/dados-certificacao'
    | '/dashboard'
    | '/profile'
    | '/_authenticated/recursos'
    | '/admin/acoes'
    | '/admin/manager'
    | '/admin/programas'
    | '/entidade/dashboard'
    | '/inscricao/$token'
    | '/_authenticated/actions/$id'
    | '/_authenticated/admin/recursos'
    | '/api/public/recursos/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ActionsRoute: typeof ActionsRoute
  AuthRoute: typeof AuthRoute
  DadosCertificacaoRoute: typeof DadosCertificacaoRoute
  DashboardRoute: typeof DashboardRoute
  ProfileRoute: typeof ProfileRoute
  AdminAcoesRoute: typeof AdminAcoesRoute
  AdminManagerRoute: typeof AdminManagerRoute
  AdminProgramasRoute: typeof AdminProgramasRoute
  EntidadeDashboardRoute: typeof EntidadeDashboardRoute
  InscricaoTokenRoute: typeof InscricaoTokenRoute
  ApiPublicRecursosSplatRoute: typeof ApiPublicRecursosSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dados-certificacao': {
      id: '/dados-certificacao'
      path: '/dados-certificacao'
      fullPath: '/dados-certificacao'
      preLoaderRoute: typeof DadosCertificacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions': {
      id: '/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof ActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricao/$token': {
      id: '/inscricao/$token'
      path: '/inscricao/$token'
      fullPath: '/inscricao/$token'
      preLoaderRoute: typeof InscricaoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entidade/dashboard': {
      id: '/entidade/dashboard'
      path: '/entidade/dashboard'
      fullPath: '/entidade/dashboard'
      preLoaderRoute: typeof EntidadeDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/programas': {
      id: '/admin/programas'
      path: '/admin/programas'
      fullPath: '/admin/programas'
      preLoaderRoute: typeof AdminProgramasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/manager': {
      id: '/admin/manager'
      path: '/admin/manager'
      fullPath: '/admin/manager'
      preLoaderRoute: typeof AdminManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/acoes': {
      id: '/admin/acoes'
      path: '/admin/acoes'
      fullPath: '/admin/acoes'
      preLoaderRoute: typeof AdminAcoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/recursos': {
      id: '/_authenticated/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof AuthenticatedRecursosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/recursos': {
      id: '/_authenticated/admin/recursos'
      path: '/admin/recursos'
      fullPath: '/admin/recursos'
      preLoaderRoute: typeof AuthenticatedAdminRecursosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/actions/$id': {
      id: '/_authenticated/actions/$id'
      path: '/actions/$id'
      fullPath: '/actions/$id'
      preLoaderRoute: typeof AuthenticatedActionsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/recursos/$': {
      id: '/api/public/recursos/$'
      path: '/api/public/recursos/$'
      fullPath: '/api/public/recursos/$'
      preLoaderRoute: typeof ApiPublicRecursosSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedRecursosRoute: typeof AuthenticatedRecursosRoute
  AuthenticatedActionsIdRoute: typeof AuthenticatedActionsIdRoute
  AuthenticatedAdminRecursosRoute: typeof AuthenticatedAdminRecursosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedRecursosRoute: AuthenticatedRecursosRoute,
  AuthenticatedActionsIdRoute: AuthenticatedActionsIdRoute,
  AuthenticatedAdminRecursosRoute: AuthenticatedAdminRecursosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ActionsRoute: ActionsRoute,
  AuthRoute: AuthRoute,
  DadosCertificacaoRoute: DadosCertificacaoRoute,
  DashboardRoute: DashboardRoute,
  ProfileRoute: ProfileRoute,
  AdminAcoesRoute: AdminAcoesRoute,
  AdminManagerRoute: AdminManagerRoute,
  AdminProgramasRoute: AdminProgramasRoute,
  EntidadeDashboardRoute: EntidadeDashboardRoute,
  InscricaoTokenRoute: InscricaoTokenRoute,
  ApiPublicRecursosSplatRoute: ApiPublicRecursosSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
