/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ElearningRouteImport } from './routes/elearning'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DadosCertificacaoRouteImport } from './routes/dados-certificacao'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ActionsRouteImport } from './routes/actions'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicacoesRevistasRouteImport } from './routes/publicacoes.revistas'
import { Route as PublicacoesIpavRouteImport } from './routes/publicacoes.ipav'
import { Route as PublicacoesBibliotecaRouteImport } from './routes/publicacoes.biblioteca'
import { Route as InscricaoTokenRouteImport } from './routes/inscricao.$token'
import { Route as EventoIdRouteImport } from './routes/evento.$id'
import { Route as EntidadeDashboardRouteImport } from './routes/entidade.dashboard'
import { Route as ConviteTokenRouteImport } from './routes/convite.$token'
import { Route as ComunicacaoPropriedadeIntelectualRouteImport } from './routes/comunicacao.propriedade-intelectual'
import { Route as ComunicacaoPressMediaKitRouteImport } from './routes/comunicacao.press-media-kit'
import { Route as AdminProgramasRouteImport } from './routes/admin.programas'
import { Route as AdminManagerRouteImport } from './routes/admin.manager'
import { Route as AdminGovernacaoRouteImport } from './routes/admin.governacao'
import { Route as AdminBadgesRouteImport } from './routes/admin.badges'
import { Route as AdminAcoesRouteImport } from './routes/admin.acoes'
import { Route as AuthenticatedRecursosRouteImport } from './routes/_authenticated/recursos'
import { Route as AuthenticatedRecursosIndexRouteImport } from './routes/_authenticated/recursos.index'
import { Route as PublicacoesRevistasIdRouteImport } from './routes/publicacoes.revistas.$id'
import { Route as EntidadeAcoesIdRouteImport } from './routes/entidade.acoes.$id'
import { Route as AuthenticatedRecursosClusterRouteImport } from './routes/_authenticated/recursos.$cluster'
import { Route as AuthenticatedAdminRecursosRouteImport } from './routes/_authenticated/admin.recursos'
import { Route as AuthenticatedActionsIdRouteImport } from './routes/_authenticated/actions.$id'
import { Route as AuthenticatedRecursosClusterIndexRouteImport } from './routes/_authenticated/recursos.$cluster.index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiCertificatesActionIdParticipanteIdRouteImport } from './routes/api/certificates.$actionId.$participanteId'
import { Route as AuthenticatedRecursosClusterTemaIdRouteImport } from './routes/_authenticated/recursos.$cluster.$temaId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ElearningRoute = ElearningRouteImport.update({
  id: '/elearning',
  path: '/elearning',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DadosCertificacaoRoute = DadosCertificacaoRouteImport.update({
  id: '/dados-certificacao',
  path: '/dados-certificacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsRoute = ActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicacoesRevistasRoute = PublicacoesRevistasRouteImport.update({
  id: '/publicacoes/revistas',
  path: '/publicacoes/revistas',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicacoesIpavRoute = PublicacoesIpavRouteImport.update({
  id: '/publicacoes/ipav',
  path: '/publicacoes/ipav',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicacoesBibliotecaRoute = PublicacoesBibliotecaRouteImport.update({
  id: '/publicacoes/biblioteca',
  path: '/publicacoes/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricaoTokenRoute = InscricaoTokenRouteImport.update({
  id: '/inscricao/$token',
  path: '/inscricao/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EventoIdRoute = EventoIdRouteImport.update({
  id: '/evento/$id',
  path: '/evento/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EntidadeDashboardRoute = EntidadeDashboardRouteImport.update({
  id: '/entidade/dashboard',
  path: '/entidade/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunicacaoPropriedadeIntelectualRoute =
  ComunicacaoPropriedadeIntelectualRouteImport.update({
    id: '/comunicacao/propriedade-intelectual',
    path: '/comunicacao/propriedade-intelectual',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComunicacaoPressMediaKitRoute =
  ComunicacaoPressMediaKitRouteImport.update({
    id: '/comunicacao/press-media-kit',
    path: '/comunicacao/press-media-kit',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminProgramasRoute = AdminProgramasRouteImport.update({
  id: '/admin/programas',
  path: '/admin/programas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminManagerRoute = AdminManagerRouteImport.update({
  id: '/admin/manager',
  path: '/admin/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGovernacaoRoute = AdminGovernacaoRouteImport.update({
  id: '/admin/governacao',
  path: '/admin/governacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBadgesRoute = AdminBadgesRouteImport.update({
  id: '/admin/badges',
  path: '/admin/badges',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAcoesRoute = AdminAcoesRouteImport.update({
  id: '/admin/acoes',
  path: '/admin/acoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRecursosRoute = AuthenticatedRecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecursosIndexRoute =
  AuthenticatedRecursosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRecursosRoute,
  } as any)
const PublicacoesRevistasIdRoute = PublicacoesRevistasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PublicacoesRevistasRoute,
} as any)
const EntidadeAcoesIdRoute = EntidadeAcoesIdRouteImport.update({
  id: '/entidade/acoes/$id',
  path: '/entidade/acoes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRecursosClusterRoute =
  AuthenticatedRecursosClusterRouteImport.update({
    id: '/$cluster',
    path: '/$cluster',
    getParentRoute: () => AuthenticatedRecursosRoute,
  } as any)
const AuthenticatedAdminRecursosRoute =
  AuthenticatedAdminRecursosRouteImport.update({
    id: '/admin/recursos',
    path: '/admin/recursos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedActionsIdRoute = AuthenticatedActionsIdRouteImport.update({
  id: '/actions/$id',
  path: '/actions/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecursosClusterIndexRoute =
  AuthenticatedRecursosClusterIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRecursosClusterRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCertificatesActionIdParticipanteIdRoute =
  ApiCertificatesActionIdParticipanteIdRouteImport.update({
    id: '/api/certificates/$actionId/$participanteId',
    path: '/api/certificates/$actionId/$participanteId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedRecursosClusterTemaIdRoute =
  AuthenticatedRecursosClusterTemaIdRouteImport.update({
    id: '/$temaId',
    path: '/$temaId',
    getParentRoute: () => AuthenticatedRecursosClusterRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/auth': typeof AuthRoute
  '/dados-certificacao': typeof DadosCertificacaoRoute
  '/dashboard': typeof DashboardRoute
  '/elearning': typeof ElearningRoute
  '/faqs': typeof FaqsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/recursos': typeof AuthenticatedRecursosRouteWithChildren
  '/admin/acoes': typeof AdminAcoesRoute
  '/admin/badges': typeof AdminBadgesRoute
  '/admin/governacao': typeof AdminGovernacaoRoute
  '/admin/manager': typeof AdminManagerRoute
  '/admin/programas': typeof AdminProgramasRoute
  '/comunicacao/press-media-kit': typeof ComunicacaoPressMediaKitRoute
  '/comunicacao/propriedade-intelectual': typeof ComunicacaoPropriedadeIntelectualRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/entidade/dashboard': typeof EntidadeDashboardRoute
  '/evento/$id': typeof EventoIdRoute
  '/inscricao/$token': typeof InscricaoTokenRoute
  '/publicacoes/biblioteca': typeof PublicacoesBibliotecaRoute
  '/publicacoes/ipav': typeof PublicacoesIpavRoute
  '/publicacoes/revistas': typeof PublicacoesRevistasRouteWithChildren
  '/actions/$id': typeof AuthenticatedActionsIdRoute
  '/admin/recursos': typeof AuthenticatedAdminRecursosRoute
  '/recursos/$cluster': typeof AuthenticatedRecursosClusterRouteWithChildren
  '/entidade/acoes/$id': typeof EntidadeAcoesIdRoute
  '/publicacoes/revistas/$id': typeof PublicacoesRevistasIdRoute
  '/recursos/': typeof AuthenticatedRecursosIndexRoute
  '/recursos/$cluster/$temaId': typeof AuthenticatedRecursosClusterTemaIdRoute
  '/api/certificates/$actionId/$participanteId': typeof ApiCertificatesActionIdParticipanteIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/recursos/$cluster/': typeof AuthenticatedRecursosClusterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/auth': typeof AuthRoute
  '/dados-certificacao': typeof DadosCertificacaoRoute
  '/dashboard': typeof DashboardRoute
  '/elearning': typeof ElearningRoute
  '/faqs': typeof FaqsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/acoes': typeof AdminAcoesRoute
  '/admin/badges': typeof AdminBadgesRoute
  '/admin/governacao': typeof AdminGovernacaoRoute
  '/admin/manager': typeof AdminManagerRoute
  '/admin/programas': typeof AdminProgramasRoute
  '/comunicacao/press-media-kit': typeof ComunicacaoPressMediaKitRoute
  '/comunicacao/propriedade-intelectual': typeof ComunicacaoPropriedadeIntelectualRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/entidade/dashboard': typeof EntidadeDashboardRoute
  '/evento/$id': typeof EventoIdRoute
  '/inscricao/$token': typeof InscricaoTokenRoute
  '/publicacoes/biblioteca': typeof PublicacoesBibliotecaRoute
  '/publicacoes/ipav': typeof PublicacoesIpavRoute
  '/publicacoes/revistas': typeof PublicacoesRevistasRouteWithChildren
  '/actions/$id': typeof AuthenticatedActionsIdRoute
  '/admin/recursos': typeof AuthenticatedAdminRecursosRoute
  '/entidade/acoes/$id': typeof EntidadeAcoesIdRoute
  '/publicacoes/revistas/$id': typeof PublicacoesRevistasIdRoute
  '/recursos': typeof AuthenticatedRecursosIndexRoute
  '/recursos/$cluster/$temaId': typeof AuthenticatedRecursosClusterTemaIdRoute
  '/api/certificates/$actionId/$participanteId': typeof ApiCertificatesActionIdParticipanteIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/recursos/$cluster': typeof AuthenticatedRecursosClusterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/actions': typeof ActionsRoute
  '/auth': typeof AuthRoute
  '/dados-certificacao': typeof DadosCertificacaoRoute
  '/dashboard': typeof DashboardRoute
  '/elearning': typeof ElearningRoute
  '/faqs': typeof FaqsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/recursos': typeof AuthenticatedRecursosRouteWithChildren
  '/admin/acoes': typeof AdminAcoesRoute
  '/admin/badges': typeof AdminBadgesRoute
  '/admin/governacao': typeof AdminGovernacaoRoute
  '/admin/manager': typeof AdminManagerRoute
  '/admin/programas': typeof AdminProgramasRoute
  '/comunicacao/press-media-kit': typeof ComunicacaoPressMediaKitRoute
  '/comunicacao/propriedade-intelectual': typeof ComunicacaoPropriedadeIntelectualRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/entidade/dashboard': typeof EntidadeDashboardRoute
  '/evento/$id': typeof EventoIdRoute
  '/inscricao/$token': typeof InscricaoTokenRoute
  '/publicacoes/biblioteca': typeof PublicacoesBibliotecaRoute
  '/publicacoes/ipav': typeof PublicacoesIpavRoute
  '/publicacoes/revistas': typeof PublicacoesRevistasRouteWithChildren
  '/_authenticated/actions/$id': typeof AuthenticatedActionsIdRoute
  '/_authenticated/admin/recursos': typeof AuthenticatedAdminRecursosRoute
  '/_authenticated/recursos/$cluster': typeof AuthenticatedRecursosClusterRouteWithChildren
  '/entidade/acoes/$id': typeof EntidadeAcoesIdRoute
  '/publicacoes/revistas/$id': typeof PublicacoesRevistasIdRoute
  '/_authenticated/recursos/': typeof AuthenticatedRecursosIndexRoute
  '/_authenticated/recursos/$cluster/$temaId': typeof AuthenticatedRecursosClusterTemaIdRoute
  '/api/certificates/$actionId/$participanteId': typeof ApiCertificatesActionIdParticipanteIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_authenticated/recursos/$cluster/': typeof AuthenticatedRecursosClusterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actions'
    | '/auth'
    | '/dados-certificacao'
    | '/dashboard'
    | '/elearning'
    | '/faqs'
    | '/profile'
    | '/reset-password'
    | '/recursos'
    | '/admin/acoes'
    | '/admin/badges'
    | '/admin/governacao'
    | '/admin/manager'
    | '/admin/programas'
    | '/comunicacao/press-media-kit'
    | '/comunicacao/propriedade-intelectual'
    | '/convite/$token'
    | '/entidade/dashboard'
    | '/evento/$id'
    | '/inscricao/$token'
    | '/publicacoes/biblioteca'
    | '/publicacoes/ipav'
    | '/publicacoes/revistas'
    | '/actions/$id'
    | '/admin/recursos'
    | '/recursos/$cluster'
    | '/entidade/acoes/$id'
    | '/publicacoes/revistas/$id'
    | '/recursos/'
    | '/recursos/$cluster/$temaId'
    | '/api/certificates/$actionId/$participanteId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/recursos/$cluster/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actions'
    | '/auth'
    | '/dados-certificacao'
    | '/dashboard'
    | '/elearning'
    | '/faqs'
    | '/profile'
    | '/reset-password'
    | '/admin/acoes'
    | '/admin/badges'
    | '/admin/governacao'
    | '/admin/manager'
    | '/admin/programas'
    | '/comunicacao/press-media-kit'
    | '/comunicacao/propriedade-intelectual'
    | '/convite/$token'
    | '/entidade/dashboard'
    | '/evento/$id'
    | '/inscricao/$token'
    | '/publicacoes/biblioteca'
    | '/publicacoes/ipav'
    | '/publicacoes/revistas'
    | '/actions/$id'
    | '/admin/recursos'
    | '/entidade/acoes/$id'
    | '/publicacoes/revistas/$id'
    | '/recursos'
    | '/recursos/$cluster/$temaId'
    | '/api/certificates/$actionId/$participanteId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/recursos/$cluster'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/actions'
    | '/auth'
    | '/dados-certificacao'
    | '/dashboard'
    | '/elearning'
    | '/faqs'
    | '/profile'
    | '/reset-password'
    | '/_authenticated/recursos'
    | '/admin/acoes'
    | '/admin/badges'
    | '/admin/governacao'
    | '/admin/manager'
    | '/admin/programas'
    | '/comunicacao/press-media-kit'
    | '/comunicacao/propriedade-intelectual'
    | '/convite/$token'
    | '/entidade/dashboard'
    | '/evento/$id'
    | '/inscricao/$token'
    | '/publicacoes/biblioteca'
    | '/publicacoes/ipav'
    | '/publicacoes/revistas'
    | '/_authenticated/actions/$id'
    | '/_authenticated/admin/recursos'
    | '/_authenticated/recursos/$cluster'
    | '/entidade/acoes/$id'
    | '/publicacoes/revistas/$id'
    | '/_authenticated/recursos/'
    | '/_authenticated/recursos/$cluster/$temaId'
    | '/api/certificates/$actionId/$participanteId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/_authenticated/recursos/$cluster/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ActionsRoute: typeof ActionsRoute
  AuthRoute: typeof AuthRoute
  DadosCertificacaoRoute: typeof DadosCertificacaoRoute
  DashboardRoute: typeof DashboardRoute
  ElearningRoute: typeof ElearningRoute
  FaqsRoute: typeof FaqsRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AdminAcoesRoute: typeof AdminAcoesRoute
  AdminBadgesRoute: typeof AdminBadgesRoute
  AdminGovernacaoRoute: typeof AdminGovernacaoRoute
  AdminManagerRoute: typeof AdminManagerRoute
  AdminProgramasRoute: typeof AdminProgramasRoute
  ComunicacaoPressMediaKitRoute: typeof ComunicacaoPressMediaKitRoute
  ComunicacaoPropriedadeIntelectualRoute: typeof ComunicacaoPropriedadeIntelectualRoute
  ConviteTokenRoute: typeof ConviteTokenRoute
  EntidadeDashboardRoute: typeof EntidadeDashboardRoute
  EventoIdRoute: typeof EventoIdRoute
  InscricaoTokenRoute: typeof InscricaoTokenRoute
  PublicacoesBibliotecaRoute: typeof PublicacoesBibliotecaRoute
  PublicacoesIpavRoute: typeof PublicacoesIpavRoute
  PublicacoesRevistasRoute: typeof PublicacoesRevistasRouteWithChildren
  EntidadeAcoesIdRoute: typeof EntidadeAcoesIdRoute
  ApiCertificatesActionIdParticipanteIdRoute: typeof ApiCertificatesActionIdParticipanteIdRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elearning': {
      id: '/elearning'
      path: '/elearning'
      fullPath: '/elearning'
      preLoaderRoute: typeof ElearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dados-certificacao': {
      id: '/dados-certificacao'
      path: '/dados-certificacao'
      fullPath: '/dados-certificacao'
      preLoaderRoute: typeof DadosCertificacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions': {
      id: '/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof ActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicacoes/revistas': {
      id: '/publicacoes/revistas'
      path: '/publicacoes/revistas'
      fullPath: '/publicacoes/revistas'
      preLoaderRoute: typeof PublicacoesRevistasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicacoes/ipav': {
      id: '/publicacoes/ipav'
      path: '/publicacoes/ipav'
      fullPath: '/publicacoes/ipav'
      preLoaderRoute: typeof PublicacoesIpavRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicacoes/biblioteca': {
      id: '/publicacoes/biblioteca'
      path: '/publicacoes/biblioteca'
      fullPath: '/publicacoes/biblioteca'
      preLoaderRoute: typeof PublicacoesBibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricao/$token': {
      id: '/inscricao/$token'
      path: '/inscricao/$token'
      fullPath: '/inscricao/$token'
      preLoaderRoute: typeof InscricaoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evento/$id': {
      id: '/evento/$id'
      path: '/evento/$id'
      fullPath: '/evento/$id'
      preLoaderRoute: typeof EventoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entidade/dashboard': {
      id: '/entidade/dashboard'
      path: '/entidade/dashboard'
      fullPath: '/entidade/dashboard'
      preLoaderRoute: typeof EntidadeDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunicacao/propriedade-intelectual': {
      id: '/comunicacao/propriedade-intelectual'
      path: '/comunicacao/propriedade-intelectual'
      fullPath: '/comunicacao/propriedade-intelectual'
      preLoaderRoute: typeof ComunicacaoPropriedadeIntelectualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunicacao/press-media-kit': {
      id: '/comunicacao/press-media-kit'
      path: '/comunicacao/press-media-kit'
      fullPath: '/comunicacao/press-media-kit'
      preLoaderRoute: typeof ComunicacaoPressMediaKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/programas': {
      id: '/admin/programas'
      path: '/admin/programas'
      fullPath: '/admin/programas'
      preLoaderRoute: typeof AdminProgramasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/manager': {
      id: '/admin/manager'
      path: '/admin/manager'
      fullPath: '/admin/manager'
      preLoaderRoute: typeof AdminManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/governacao': {
      id: '/admin/governacao'
      path: '/admin/governacao'
      fullPath: '/admin/governacao'
      preLoaderRoute: typeof AdminGovernacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/badges': {
      id: '/admin/badges'
      path: '/admin/badges'
      fullPath: '/admin/badges'
      preLoaderRoute: typeof AdminBadgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/acoes': {
      id: '/admin/acoes'
      path: '/admin/acoes'
      fullPath: '/admin/acoes'
      preLoaderRoute: typeof AdminAcoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/recursos': {
      id: '/_authenticated/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof AuthenticatedRecursosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recursos/': {
      id: '/_authenticated/recursos/'
      path: '/'
      fullPath: '/recursos/'
      preLoaderRoute: typeof AuthenticatedRecursosIndexRouteImport
      parentRoute: typeof AuthenticatedRecursosRoute
    }
    '/publicacoes/revistas/$id': {
      id: '/publicacoes/revistas/$id'
      path: '/$id'
      fullPath: '/publicacoes/revistas/$id'
      preLoaderRoute: typeof PublicacoesRevistasIdRouteImport
      parentRoute: typeof PublicacoesRevistasRoute
    }
    '/entidade/acoes/$id': {
      id: '/entidade/acoes/$id'
      path: '/entidade/acoes/$id'
      fullPath: '/entidade/acoes/$id'
      preLoaderRoute: typeof EntidadeAcoesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/recursos/$cluster': {
      id: '/_authenticated/recursos/$cluster'
      path: '/$cluster'
      fullPath: '/recursos/$cluster'
      preLoaderRoute: typeof AuthenticatedRecursosClusterRouteImport
      parentRoute: typeof AuthenticatedRecursosRoute
    }
    '/_authenticated/admin/recursos': {
      id: '/_authenticated/admin/recursos'
      path: '/admin/recursos'
      fullPath: '/admin/recursos'
      preLoaderRoute: typeof AuthenticatedAdminRecursosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/actions/$id': {
      id: '/_authenticated/actions/$id'
      path: '/actions/$id'
      fullPath: '/actions/$id'
      preLoaderRoute: typeof AuthenticatedActionsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recursos/$cluster/': {
      id: '/_authenticated/recursos/$cluster/'
      path: '/'
      fullPath: '/recursos/$cluster/'
      preLoaderRoute: typeof AuthenticatedRecursosClusterIndexRouteImport
      parentRoute: typeof AuthenticatedRecursosClusterRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/certificates/$actionId/$participanteId': {
      id: '/api/certificates/$actionId/$participanteId'
      path: '/api/certificates/$actionId/$participanteId'
      fullPath: '/api/certificates/$actionId/$participanteId'
      preLoaderRoute: typeof ApiCertificatesActionIdParticipanteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/recursos/$cluster/$temaId': {
      id: '/_authenticated/recursos/$cluster/$temaId'
      path: '/$temaId'
      fullPath: '/recursos/$cluster/$temaId'
      preLoaderRoute: typeof AuthenticatedRecursosClusterTemaIdRouteImport
      parentRoute: typeof AuthenticatedRecursosClusterRoute
    }
  }
}

interface AuthenticatedRecursosClusterRouteChildren {
  AuthenticatedRecursosClusterTemaIdRoute: typeof AuthenticatedRecursosClusterTemaIdRoute
  AuthenticatedRecursosClusterIndexRoute: typeof AuthenticatedRecursosClusterIndexRoute
}

const AuthenticatedRecursosClusterRouteChildren: AuthenticatedRecursosClusterRouteChildren =
  {
    AuthenticatedRecursosClusterTemaIdRoute:
      AuthenticatedRecursosClusterTemaIdRoute,
    AuthenticatedRecursosClusterIndexRoute:
      AuthenticatedRecursosClusterIndexRoute,
  }

const AuthenticatedRecursosClusterRouteWithChildren =
  AuthenticatedRecursosClusterRoute._addFileChildren(
    AuthenticatedRecursosClusterRouteChildren,
  )

interface AuthenticatedRecursosRouteChildren {
  AuthenticatedRecursosClusterRoute: typeof AuthenticatedRecursosClusterRouteWithChildren
  AuthenticatedRecursosIndexRoute: typeof AuthenticatedRecursosIndexRoute
}

const AuthenticatedRecursosRouteChildren: AuthenticatedRecursosRouteChildren = {
  AuthenticatedRecursosClusterRoute:
    AuthenticatedRecursosClusterRouteWithChildren,
  AuthenticatedRecursosIndexRoute: AuthenticatedRecursosIndexRoute,
}

const AuthenticatedRecursosRouteWithChildren =
  AuthenticatedRecursosRoute._addFileChildren(
    AuthenticatedRecursosRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedRecursosRoute: typeof AuthenticatedRecursosRouteWithChildren
  AuthenticatedActionsIdRoute: typeof AuthenticatedActionsIdRoute
  AuthenticatedAdminRecursosRoute: typeof AuthenticatedAdminRecursosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedRecursosRoute: AuthenticatedRecursosRouteWithChildren,
  AuthenticatedActionsIdRoute: AuthenticatedActionsIdRoute,
  AuthenticatedAdminRecursosRoute: AuthenticatedAdminRecursosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicacoesRevistasRouteChildren {
  PublicacoesRevistasIdRoute: typeof PublicacoesRevistasIdRoute
}

const PublicacoesRevistasRouteChildren: PublicacoesRevistasRouteChildren = {
  PublicacoesRevistasIdRoute: PublicacoesRevistasIdRoute,
}

const PublicacoesRevistasRouteWithChildren =
  PublicacoesRevistasRoute._addFileChildren(PublicacoesRevistasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ActionsRoute: ActionsRoute,
  AuthRoute: AuthRoute,
  DadosCertificacaoRoute: DadosCertificacaoRoute,
  DashboardRoute: DashboardRoute,
  ElearningRoute: ElearningRoute,
  FaqsRoute: FaqsRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AdminAcoesRoute: AdminAcoesRoute,
  AdminBadgesRoute: AdminBadgesRoute,
  AdminGovernacaoRoute: AdminGovernacaoRoute,
  AdminManagerRoute: AdminManagerRoute,
  AdminProgramasRoute: AdminProgramasRoute,
  ComunicacaoPressMediaKitRoute: ComunicacaoPressMediaKitRoute,
  ComunicacaoPropriedadeIntelectualRoute:
    ComunicacaoPropriedadeIntelectualRoute,
  ConviteTokenRoute: ConviteTokenRoute,
  EntidadeDashboardRoute: EntidadeDashboardRoute,
  EventoIdRoute: EventoIdRoute,
  InscricaoTokenRoute: InscricaoTokenRoute,
  PublicacoesBibliotecaRoute: PublicacoesBibliotecaRoute,
  PublicacoesIpavRoute: PublicacoesIpavRoute,
  PublicacoesRevistasRoute: PublicacoesRevistasRouteWithChildren,
  EntidadeAcoesIdRoute: EntidadeAcoesIdRoute,
  ApiCertificatesActionIdParticipanteIdRoute:
    ApiCertificatesActionIdParticipanteIdRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
