REVOKE EXECUTE ON FUNCTION public.anonimizar_utilizador(uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.apply_invite_to_user(text, uuid, uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.auto_grant_program_badge() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.auto_grant_role_badges() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.auto_provision_entity_program_cohort() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.compute_user_badge_expiry() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.email_queue_dispatch() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.email_queue_wake() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_update_timestamp() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.has_role(uuid, text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.is_admin(uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.is_equipa(uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.move_to_dlq(text, text, bigint, jsonb) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.prevent_profile_privilege_change() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.prevent_role_self_escalation() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.protect_system_roles() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.read_email_batch(text, integer, integer) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.sync_primary_role() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.user_can_access_cluster(uuid, uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.user_can_access_recurso(uuid, uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.anonimizar_utilizador(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.apply_invite_to_user(text, uuid, uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.auto_grant_program_badge() TO service_role;
GRANT EXECUTE ON FUNCTION public.auto_grant_role_badges() TO service_role;
GRANT EXECUTE ON FUNCTION public.auto_grant_program_badge() TO postgres;
GRANT EXECUTE ON FUNCTION public.auto_grant_role_badges() TO postgres;
GRANT EXECUTE ON FUNCTION public.auto_provision_entity_program_cohort() TO postgres;
GRANT EXECUTE ON FUNCTION public.compute_user_badge_expiry() TO postgres;
GRANT EXECUTE ON FUNCTION public.email_queue_dispatch() TO service_role;
GRANT EXECUTE ON FUNCTION public.email_queue_wake() TO postgres;
GRANT EXECUTE ON FUNCTION public.handle_new_user() TO postgres;
GRANT EXECUTE ON FUNCTION public.handle_update_timestamp() TO postgres;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.is_admin(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.is_equipa(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.move_to_dlq(text, text, bigint, jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.prevent_profile_privilege_change() TO postgres;
GRANT EXECUTE ON FUNCTION public.prevent_role_self_escalation() TO postgres;
GRANT EXECUTE ON FUNCTION public.protect_system_roles() TO postgres;
GRANT EXECUTE ON FUNCTION public.read_email_batch(text, integer, integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.sync_primary_role() TO postgres;
GRANT EXECUTE ON FUNCTION public.user_can_access_cluster(uuid, uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.user_can_access_recurso(uuid, uuid) TO service_role;